#       _       _       __  __
#      | |     (_)     |  \/  |
#      | | ___  _ _ __ | \  / | ___  ___ ___  __ _  __ _  ___
#  _   | |/ _ \| | '_ \| |\/| |/ _ \/ __/ __|/ _` |/ _` |/ _ \
# | |__| | (_) | | | | | |  | |  __/\__ \__ \ (_| | (_| |  __/
#  \____/ \___/|_|_| |_|_|  |_|\___||___/___/\__,_|\__, |\___|
#                                                   __/ |
#                                                  |___/

config-version: 1.1 # Do not Touch this line!
update-checker: true

server-name: YourServerName
ip: play.yourserver.com

forum:
  - ''
store:
  - ''
website:
  - ''
discord:
  - ''
info:
  - ''
social-media:
  - 'Tiktok : @YourTiktokName'
  - 'Twitter : @YourTwitterName'
  - 'Instagram : @YourInstagramName'
  - 'Youtube : YourYoutubeChannel'
options:
  social-media-enabled: true
  discord-enabled: true
  forums-enabled: true
  store-enabled: true
  website-enabled: true
  info-enabled: true

player:
  on-join: '&7[&a+&7] &e%player% &aJoined the server'
  on-quit: '&7[&a-&7] &e%player% &cDisconnect from the server'

chat:
  enabled: true
  permission: false
  message:
    - '&8=========================================='
    - '&5Hello: %player%'
    - '&cServer name: %server-name%'
    - '&6Players: %online-players% / Max players: %max-players%'
    - '&aServer version: %server-version%'
    - '&aYou can put as many lines as you want, edit in config.yml'
    - '&aPlugin by : &6&lClueForce'
    - '&aThanks for downloading this plugin'
    - '&aDont forget to give 5 Stars in Review!'
    - '&8=========================================='

title:
  enabled: true
  permission: false
  repeattimes: 2
  delay: 30
  speed: 10
  animation:
    - '&8===> &6&lTest Server &8<==='
    - '&8===> &9&lT&6&lest Server &8<==='
    - '&8===> &9&lTe&6&lst Server &8<==='
    - '&8===> &9&lTes&6&lt Server &8<==='
    - '&8===> &9&lTest &6&lServer &8<==='
    - '&8===> &9&lTest S&6&lerver &8<==='
    - '&8===> &9&lTest Se&6&lrver &8<==='
    - '&8===> &9&lTest Ser&6&lver &8<==='
    - '&8===> &9&lTest Serv&6&ler &8<==='
    - '&8===> &9&lTest Serve&6&lr &8<==='
    - '&8===> &9&lTest Serv&6&ler &8<==='
    - '&8===> &9&lTest Ser&6&lver &8<==='
    - '&8===> &9&lTest Se&6&lrver &8<==='
    - '&8===> &9&lTest S&6&lerver &8<==='
    - '&8===> &9&lTest &6&lServer &8<==='
    - '&8===> &9&lTes&6&lt Server &8<==='
    - '&8===> &9&lTe&6&lst Server &8<==='
    - '&8===> &9&lT&6&lest Server &8<==='

subtitle:
  enabled: true
  permission: false
  repeattimes: 2
  delay: 30
  speed: 90
  animation:
    - '&8Welcome &5&l%player%'
    - '&8Current players &5&l%online-players%/%max-players%'
    - '&8%ip%'