name: JoinMessage
version: '${project.version}'
main: me.clueforce.joinmessage.BukkitPlugin
api-version: 1.13
depend: [ PlaceholderAPI ]
authors: [ ClueForce ]
description: Join and Quit Message plugin like Hypixel Server
commands:
  joinmessage:
    aliases: jm